---

- name: run the main role
  hosts: all
  pre_tasks:
    - name: update repositories cache
      apt:
        update_cache: yes
    - package: name={{ item }} state=latest
      with_items:
        - curl
        - thin-provisioning-tools
        - mylvmbackup
        - jq
        - libfile-copy-recursive-perl
        - xinetd
        - sudo
        - iproute
        - rsyslog
        - ca-certificates
        - sudo
        - python-apt
        - software-properties-common
        - tar
        - unzip
        - bzip2
        - gzip
    - name: install percona mysql repo
      shell: curl -O https://repo.percona.com/apt/percona-release_0.1-4.$(lsb_release -sc)_all.deb && dpkg -i percona-release_0.1-4.$(lsb_release -sc)_all.deb
      args:
        creates: /etc/apt/sources.list.d/percona-release.list
        executable: /bin/bash
        chdir: /tmp
    - name: refresh apt cache
      apt:
        update_cache: yes
  roles:
    - role: entercloudsuite.consul
      consul_version: 1.2.3
      consul_packer_provision: true
      consul_configs:
        main:
          bind_addr: 0.0.0.0
          client_addr: 0.0.0.0
          node_name: "{{ ansible_hostname }}"
          data_dir: "{{ consul_data_dir }}"
          encrypt: "K8n07GA/ZoANSmJ5zkvgOg=="
          enable_syslog: true
          datacenter: automium
          server: true
          ui: true
    - role: entercloudsuite.haproxy
      haproxy_user: admin
      haproxy_pass: admin
    - role: entercloudsuite.mysql
      mysql_packages:
        - percona-server-server-5.7
      mysql_users:
        - name: orchestrator
          host: '127.0.0.1'
          password: orchestrator
          priv: '*.*:ALL'
    - role: ansible-orchestrator
      orchestrator_version: 3.0.12
      orchestrator_mysql_user: orchestrator
      orchestrator_mysql_password: orchestrator
  post_tasks:
    - name: download fixed orchestrator bin https://github.com/github/orchestrator/pull/599
      get_url:
        url: https://swift.it-mil1.entercloudsuite.com/v1/KEY_d51f5387474f40c6bd2975ccf34c7ea0/orchestratorbin/orchestrator
        dest: "/opt/orchestrator/orchestrator/usr/local/orchestrator/orchestrator"
        mode: 0755
        force: yes

- name: prepare virtualenv
  hosts: all
  tasks:
    - name: create var project path
      set_fact:
        script_path: /usr/src/cloud
    - name: install requirements
      package: name="{{ item }}"
      with_items:
        - libffi-dev
        - libssl-dev
        - python-minimal
        - python-pip
        - virtualenv
    - name: create directory
      file: path="{{ item }}" state=directory
      with_items:
        - "{{ script_path }}"
        - "{{ script_path }}/roles"
    - name: create requirements.txt
      copy:
        content: |
          ansible==2.6.2
          asn1crypto==0.23.0
          bcrypt==3.1.4
          cffi==1.11.2
          cryptography==2.1.3
          enum34==1.1.6
          idna==2.6
          ipaddress==1.0.18
          Jinja2==2.10
          MarkupSafe==1.0
          paramiko==2.4.0
          pyasn1==0.3.7
          pycparser==2.18
          pycrypto==2.6.1
          PyNaCl==1.2.0
          PyYAML==3.12
          six==1.11.0
          jmespath==0.9.3
        dest: "{{ script_path }}/requirements.txt"
        remote_src: yes
    - name: create requirements.yml
      copy:
        content: |
          - src: entercloudsuite.orchestrator
            version: 1.0.8
          - src: entercloudsuite.mysql
            version: 1.0.0
          - src: entercloudsuite.haproxy
            version: 1.1.3
          - src: entercloudsuite.consul
            version: 1.0.1
        dest: "{{ script_path }}/requirements.yml"
        remote_src: yes
    - name: install python requirements
      pip:
        requirements: "{{ script_path }}/requirements.txt"
        virtualenv: "{{ script_path }}/venv"
    - name: install ansible roles
      shell: source {{ script_path }}/venv/bin/activate && ansible-galaxy install -f -p roles -r requirements.yml
      args:
        chdir: "{{ script_path }}"
        executable: /bin/bash
